"""add academic fields

Revision ID: f6e79dec121f
Revises: f5e79dec121f
Create Date: 2026-06-08 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e79dec121f'
down_revision: Union[str, None] = '08a86459f4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('program', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('minor', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('research_project', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'research_project')
    op.drop_column('users', 'minor')
    op.drop_column('users', 'program')
    # ### end Alembic commands ###
